language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lcov
  - gem install coveralls-lcov
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_BLAS:BOOL=TRUE -DBUILD_TESTS:BOOL=TRUE -DBUILD_DOCS:BOOL=TRUE -DENABLE_COVERAGE:BOOL=TRUE ..
  - make -j2
  - ctest -j2 --output-on-failure
after_success:
  - lcov -d Tests -d Library -base-directory .. -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --remove coverage.info 'gtest*' -o coverage.info
  - cd ..
  - coveralls-lcov build/coverage.info
